language: ruby
rvm:
- 1.9.3
env:
  global:
  - S3_REGION="us-east-1"
  - S3_BUCKET_NAME="revily-web-bundle"
  - RAILS_ENV="test"
  - secure: RISOHPa+ZMQVwwH1sr7q+OxHm/uZKs0tQF+Sm6jFP1NPoUbvg1MSLFf13lSx7tZEpzxz4r/SJZK2g5XmqaSZJqoC+gLWJxQHVxgn1+MqArWpZaRjXFGL/hOi8HJBJ1yjaVw9yrp4ds4sy+hy/OTb+2iCRgSIZZR43gZAzfCqgjw=
install: "script/bootstrap"
script: "script/cibuild"
after_script: 
branches:
  only:
  - master
